package solrenewed;

import com.fs.starfarer.api.BaseModPlugin;
import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.StarSystemAPI;
import org.apache.log4j.Logger;
import solrenewed.crisis.CrisisWatcher;
import solrenewed.quest.SolQuest;

/**
 * Entry point. Sol and the Centaurus constellation are generated either when a new game is created
 * (after the sector's own procgen so we can find a free spot on the map) or, in the default "quest"
 * mode, at the end of the "Transferring Sol" quest. Everything that must survive a save/load (the
 * cryo-prison dialog hook, the meteor-shower listener, the colony-crisis watcher, the quest watcher)
 * is re-registered on every game load instead of being written into the save.
 */
public class SolRenewedModPlugin extends BaseModPlugin {

    public static final String MOD_ID = "sol_renewed";

    private static final Logger log = Global.getLogger(SolRenewedModPlugin.class);

    @Override
    public void onNewGameAfterProcGen() {
        SrSettings.reload();
        if (!SrSettings.INSTANCE.getSpawnSol()) {
            log.info("[SolRenewed] Sol generation disabled in settings.");
            return;
        }
        if (!SrSettings.INSTANCE.getSpawnAtStart()) {
            log.info("[SolRenewed] Sol will be generated by the Transferring Sol quest.");
            return;
        }
        generateSol();
    }

    /** Builds Sol and the Centauri constellation. Safe to call at any point in a game. */
    public static void generateSol() {
        try {
            SolSystem.INSTANCE.generate(Global.getSector());
        } catch (Throwable t) {
            log.error("[SolRenewed] Sol generation failed", t);
        }
        if (SrSettings.INSTANCE.getSpawnCentauri()) {
            try {
                Centauri.INSTANCE.generate(Global.getSector());
            } catch (Throwable t) {
                log.error("[SolRenewed] Centaurus generation failed", t);
            }
        }
    }

    @Override
    public void onGameLoad(boolean newGame) {
        SrSettings.reload();
        StarSystemAPI sol = SolSystem.INSTANCE.find();
        if (sol != null) {
            installSolRuntime(sol);
        } else if (SrSettings.INSTANCE.getSpawnSol()) {
            SolQuest.INSTANCE.install();
        }
    }

    /** The transient hooks Sol needs while it exists; also called right after a mid-game spawn. */
    public static void installSolRuntime(StarSystemAPI sol) {
        CryoPrison.INSTANCE.registerDialogHook();
        Relics.INSTANCE.schedule();
        if (ModCheck.INSTANCE.getHasIndEvo() && SrSettings.INSTANCE.getMeteors()) {
            MeteorShowers.INSTANCE.install(sol);
        }
        if (!Global.getSector().hasTransientScript(CrisisWatcher.class)) {
            Global.getSector().addTransientScript(new CrisisWatcher());
        }
    }
}
